export const CREATE_SCENARIO = 'CREATE_SCENARIO';
export const EDIT_SCENARIO = 'EDIT_SCENARIO';
export const DELETE_SCENARIO = 'DELETE_SCENARIO';
export const SAVE_SCENARIO = 'SAVE_SCENARIO';
export const SET_ACTIVE_PANEL = 'SET_ACTIVE_PANEL';
export const SET_ACTIVE_SIDE = 'SET_ACTIVE_SIDE';
export const UPDATE_GENERAL_SCENARIO_DATA = 'UPDATE_GENERAL_SCENARIO_DATA';
export const UPDATE_SIDE_NATIONALITIES = 'UPDATE_SIDE_NATIONALITIES';