export const CounterClasses0 = {
    INFANTRY: 'Infantry',
    SUPPORT_WEAPON: 'Support Weapon',
};

export const CounterClasses1 = {
    SMC: 'Single Man Counter',
    MMC: 'Multi-man Counter',
    MACHINE_GUN: 'Machine Gun',
    FT: 'Flamethrower',
    DC: 'Demolition Charge'
};

export const CounterClasses2 = {
    SQUAD: 'Squad',
    HALF_SQUAD: 'Half Squad',
    LEADER: 'Leader',
    LMG: 'Light Machine Gun',
    MMG: 'Medium Machine Gun',
};

export const Sides = {
    AXIS: 'Axis',
    ALLIED: 'Allied'
};

export const Nationalities = {
    AMERICAN: { label: 'American', side: Sides.ALLIED, code:'am' },
    GERMAN: { label: 'German', side: Sides.AXIS, code:'ge' },
    RUSSIAN: { label: 'Russian', side: Sides.ALLIED, code:'ru' }
};

export const CounterTypes = {
    am747S: { label: '7-4-7', nationality: Nationalities.AMERICAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.MMC, counterClass2: CounterClasses2.SQUAD, firepower: 7, range: 4, morale: 7, elrClass: 'E', reduceType: 'am337H', smoke: 3, assaultFire: true, brokenType: 'ams8b', brokenMorale: 8 },
    am337H: { label: '3-3-7', nationality: Nationalities.AMERICAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.MMC, counterClass2: CounterClasses2.HALF_SQUAD, firepower: 3, range: 3, morale: 7, elrClass: 'E', brokenType: 'amh7b', brokenMorale: 7 },
    amL81: { label: '8-1', nationality: Nationalities.AMERICAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.SMC, counterClass2: CounterClasses2.LEADER, morale: 8, selfRally: true, leadership: -1, brokenType: 'amL81b', replacementType: 'amL80', brokenMorale: 8 },
    amL80: { label: '8-0', nationality: Nationalities.AMERICAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.SMC, counterClass2: CounterClasses2.LEADER, morale: 8, selfRally: true, leadership: 0, brokenType: 'amL80b', replacementType: 'amL70', brokenMorale: 8 },
    amL70: { label: '7-0', nationality: Nationalities.AMERICAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.SMC, counterClass2: CounterClasses2.LEADER, morale: 7, selfRally: true, leadership: 0, brokenType: 'amL70b', replacementType: 'amL61', brokenMorale: 7 },
    amL61: { label: '6+1', nationality: Nationalities.AMERICAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.SMC, counterClass2: CounterClasses2.LEADER, morale: 6, selfRally: true, leadership: +1, brokenType: 'amL61b', brokenMorale: 6 },
    amL92: { label: '9-2', nationality: Nationalities.AMERICAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.SMC, counterClass2: CounterClasses2.LEADER, morale: 9, selfRally: true, leadership: -2, brokenType: 'amL92b', brokenMorale: 9 },
    amL91: { label: '9-1', nationality: Nationalities.AMERICAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.SMC, counterClass2: CounterClasses2.LEADER, morale: 9, selfRally: true, leadership: -1, brokenType: 'amL91b', brokenMorale: 9 },
    ge548S: { label: '5-4-8', nationality: Nationalities.GERMAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.MMC, counterClass2: CounterClasses2.SQUAD, firepower: 5, range: 4, morale: 8, elrClass: 'E', reduceType: 'ge238H', replacementType: 'ge447S', smoke: 2, brokenType: 'ges8b', brokenMorale: 8 },
    ge467S: { label: '4-6-7', nationality: Nationalities.GERMAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.MMC, counterClass2: CounterClasses2.SQUAD, firepower: 4, range: 6, morale: 7, elrClass: '1', reduceType: 'ge247H', replacementType: 'ge447S', smoke: 1, brokenType: 'ges7b', brokenMorale: 7 },
    ge447S: { label: '4-4-7', nationality: Nationalities.GERMAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.MMC, counterClass2: CounterClasses2.SQUAD, firepower: 4, range: 4, morale: 7, elrClass: '2', reduceType: 'ge237H', replacementType: 'ge436S', brokenType: 'ges7b', brokenMorale: 7 },
    ge436S: { label: '4-3-6', nationality: Nationalities.GERMAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.MMC, counterClass2: CounterClasses2.SQUAD, firepower: 4, range: 3, morale: 6, elrClass: 'C', reduceType: 'ge236H', brokenType: 'ges5b', brokenMorale: 5 },
    ge238H: { label: '2-3-8', nationality: Nationalities.GERMAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.MMC, counterClass2: CounterClasses2.HALF_SQUAD, firepower: 2, range: 3, morale: 8, elrClass: 'E', replacementType: 'ge237H', brokenType: 'geh7b', brokenMorale: 7 },
    ge247H: { label: '2-4-7', nationality: Nationalities.GERMAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.MMC, counterClass2: CounterClasses2.HALF_SQUAD, firepower: 2, range: 4, morale: 7, elrClass: '1', replacementType: 'ge237H', brokenType: 'geh6b', brokenMorale: 6 },
    ge237H: { label: '2-3-7', nationality: Nationalities.GERMAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.MMC, counterClass2: CounterClasses2.HALF_SQUAD, firepower: 2, range: 3, morale: 7, elrClass: '2', replacementType: 'ge236H', brokenType: 'geh6b', brokenMorale: 6 },
    ge236H: { label: '2-3-6', nationality: Nationalities.GERMAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.MMC, counterClass2: CounterClasses2.HALF_SQUAD, firepower: 2, range: 3, morale: 6, elrClass: 'C', brokenType: 'geh4b', brokenMorale: 4 },
    geL92: { label: '9-2', nationality: Nationalities.GERMAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.SMC, counterClass2: CounterClasses2.LEADER, morale: 9, selfRally: true, leadership: -2, brokenType: 'geL92b', replacementType: 'geL91', brokenMorale: 9 },
    geL91: { label: '9-1', nationality: Nationalities.GERMAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.SMC, counterClass2: CounterClasses2.LEADER, morale: 9, selfRally: true, leadership: -1, brokenType: 'geL91b', replacementType: 'geL81', brokenMorale: 9 },
    geL81: { label: '8-1', nationality: Nationalities.GERMAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.SMC, counterClass2: CounterClasses2.LEADER, morale: 8, selfRally: true, leadership: -1, brokenType: 'geL81b', replacementType: 'geL80', brokenMorale: 8 },
    geL80: { label: '8-0', nationality: Nationalities.GERMAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.SMC, counterClass2: CounterClasses2.LEADER, morale: 8, selfRally: true, leadership: 0, brokenType: 'geL80b', replacementType: 'geL70', brokenMorale: 8 },
    geL70: { label: '7-0', nationality: Nationalities.GERMAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.SMC, counterClass2: CounterClasses2.LEADER, morale: 7, selfRally: true, leadership: 0, brokenType: 'geL70b', replacementType: 'geL61', brokenMorale: 7 },
    geL61: { label: '6+1', nationality: Nationalities.GERMAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.SMC, counterClass2: CounterClasses2.LEADER, morale: 6, selfRally: true, leadership: +1, brokenType: 'geL61b', brokenMorale: 6 },
    geLMG: { label: '3-8 LMG', nationality: Nationalities.GERMAN, counterClass0: CounterClasses0.SUPPORT_WEAPON, counterClass1: CounterClasses1.MACHINE_GUN, counterClass2: CounterClasses2.LMG, firepower: 3, range: 8, rateOfFire: 1, breakdown: 12, portagePoints: 1, repair: 1, elimination: 6, brokenType: 'geLMGb', ignoreTem: false },
    geMMG: { label: '5-12 MMG', nationality: Nationalities.GERMAN, counterClass0: CounterClasses0.SUPPORT_WEAPON, counterClass1: CounterClasses1.MACHINE_GUN, counterClass2: CounterClasses2.MMG, firepower: 5, range: 12, rateOfFire: 2, breakdown: 12, portagePoints: 3, repair: 2, elimination: 6, brokenType: 'geMMGb', ignoreTem: false },
    geFT: { label: '24-1 FT', nationality: Nationalities.GERMAN, counterClass0: CounterClasses0.SUPPORT_WEAPON, counterClass1: CounterClasses1.FT, firepower: 24, range: 1, breakdown: 10, portagePoints: 1, repair: 0, brokenType: 'geFTb', ignoreTem: true },
    geDC: { label: '30-1 DC', nationality: Nationalities.GERMAN, counterClass0: CounterClasses0.SUPPORT_WEAPON, counterClass1: CounterClasses1.DC, firepower: 30, range: 1, breakdown: 12, portagePoints: 1, repair: 0, brokenType: 'geDCb', ignoreTem: true },
    ru447S: { label: '4-4-7', nationality: Nationalities.RUSSIAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.MMC, counterClass2: CounterClasses2.SQUAD, firepower: 4, range: 4, morale: 7, elrClass: '1', reduceType: 'ru237H', replacementType: 'ru426S', smoke: 0, brokenType: 'rus7b', brokenMorale: 7 },
    ru426S: { label: '4-2-6', nationality: Nationalities.RUSSIAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.MMC, counterClass2: CounterClasses2.SQUAD, firepower: 4, range: 2, morale: 6, elrClass: 'C', reduceType: 'ru226H', smoke: 0, brokenType: 'rus5b', brokenMorale: 5 },
    ru527S: { label: '5-2-7', nationality: Nationalities.RUSSIAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.MMC, counterClass2: CounterClasses2.SQUAD, firepower: 5, range: 2, morale: 7, elrClass: '1', reduceType: 'ru227H', replacementType: 'ru426S', smoke: 0, brokenType: 'rus7b', brokenMorale: 7 },
    ru237H: { label: '2-3-7', nationality: Nationalities.RUSSIAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.MMC, counterClass2: CounterClasses2.HALF_SQUAD, firepower: 2, range: 3, morale: 7, elrClass: '1', replacementType: 'ru226H', brokenType: 'ruh6b', brokenMorale: 6 },
    ru226H: { label: '2-2-6', nationality: Nationalities.RUSSIAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.MMC, counterClass2: CounterClasses2.HALF_SQUAD, firepower: 2, range: 2, morale: 6, elrClass: 'C', brokenType: 'ruh4b', brokenMorale: 4 },
    ru227H: { label: '2-2-7', nationality: Nationalities.RUSSIAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.MMC, counterClass2: CounterClasses2.HALF_SQUAD, firepower: 2, range: 2, morale: 7, elrClass: '1', replacementType: 'ru226H', brokenType: 'ruh6b', brokenMorale: 6 },
    ruL92: { label: '9-2', nationality: Nationalities.RUSSIAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.SMC, counterClass2: CounterClasses2.LEADER, morale: 9, selfRally: true, leadership: -2, brokenType: 'ruL92b', replacementType: 'ruL91', brokenMorale: 9 },
    ruL91: { label: '9-1', nationality: Nationalities.RUSSIAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.SMC, counterClass2: CounterClasses2.LEADER, morale: 9, selfRally: true, leadership: -1, brokenType: 'ruL91b', replacementType: 'ruL81', brokenMorale: 9 },
    ruL81: { label: '8-1', nationality: Nationalities.RUSSIAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.SMC, counterClass2: CounterClasses2.LEADER, morale: 8, selfRally: true, leadership: -1, brokenType: 'ruL81b', replacementType: 'ruL80', brokenMorale: 8 },
    ruL80: { label: '8-0', nationality: Nationalities.RUSSIAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.SMC, counterClass2: CounterClasses2.LEADER, morale: 8, selfRally: true, leadership: 0, brokenType: 'ruL80b', replacementType: 'ruL70', brokenMorale: 8 },
    ruL70: { label: '7-0', nationality: Nationalities.RUSSIAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.SMC, counterClass2: CounterClasses2.LEADER, morale: 7, selfRally: true, leadership: 0, brokenType: 'ruL70b', replacementType: 'ruL61', brokenMorale: 7 },
    ruL61: { label: '6+1', nationality: Nationalities.RUSSIAN, counterClass0: CounterClasses0.INFANTRY, counterClass1: CounterClasses1.SMC, counterClass2: CounterClasses2.LEADER, morale: 6, selfRally: true, leadership: +1, brokenType: 'ruL61b', brokenMorale: 6 },
    ruLMG: { label: '2-6 LMG', nationality: Nationalities.RUSSIAN, counterClass0: CounterClasses0.SUPPORT_WEAPON, counterClass1: CounterClasses1.MACHINE_GUN, counterClass2: CounterClasses2.LMG, firepower: 2, range: 6, rateOfFire: 1, breakdown: 11, portagePoints: 1, repair: 1, elimination: 6, brokenType: 'ruLMGb', ignoreTem: false },
    ruMMG: { label: '4-10 MMG', nationality: Nationalities.RUSSIAN, counterClass0: CounterClasses0.SUPPORT_WEAPON, counterClass1: CounterClasses1.MACHINE_GUN, counterClass2: CounterClasses2.MMG, firepower: 4, range: 10, rateOfFire: 2, breakdown: 11, portagePoints: 5, repair: 2, elimination: 6, brokenType: 'ruMMGb', ignoreTem: false },
};

export const ImageMap = {
    geL92: { src: '/images/counters/ge/geL92.gif' },
    geL92b: { src: '/images/counters/ge/geL92b.gif' },
    geLMG: { src: '/images/counters/ge/geLMG.gif' },
    geLMGb: { src: '/images/counters/ge/geLMGb.gif' },
    geMMG: { src: '/images/counters/ge/geMMG.gif' },
    geMMGb: { src: '/images/counters/ge/geMMGb.gif' },
    geFT: { src: '/images/counters/ge/geFT.gif' },
    geFTb: { src: '/images/counters/ge/geFTb.gif' },
    geDC: { src: '/images/counters/ge/geDC.gif' },
    geDCb: { src: '/images/counters/ge/geDCb.gif' },

    ru447S: { src: '/images/counters/ru/ru447S.gif' },
    rus7b: { src: '/images/counters/ru/rus7b.gif' },
    ru426S: { src: '/images/counters/ru/ru426S.gif' },
    rus5b: { src: '/images/counters/ru/rus5b.gif' },
    ru527S: { src: '/images/counters/ru/ru527S.gif' },
    ru237H: { src: '/images/counters/ru/ru237H.gif' },
    ruh6b: { src: '/images/counters/ru/ruh6b.gif' },
    ru226H: { src: '/images/counters/ru/ru226H.gif' },
    ruh4b: { src: '/images/counters/ru/ruh4b.gif' },
    ru227H: { src: '/images/counters/ru/ru227H.gif' },
    ruL92: { src: '/images/counters/ru/ruL92.gif' },
    ruL92b: { src: '/images/counters/ru/ruL92b.gif' },
    ruL91: { src: '/images/counters/ru/ruL91.gif' },
    ruL91b: { src: '/images/counters/ru/ruL91b.gif' },
    ruL81: { src: '/images/counters/ru/ruL81.gif' },
    ruL81b: { src: '/images/counters/ru/ruL81b.gif' },
    ruL80: { src: '/images/counters/ru/ruL80.gif' },
    ruL80b: { src: '/images/counters/ru/ruL80b.gif' },
    ruL70: { src: '/images/counters/ru/ruL70.gif' },
    ruL70b: { src: '/images/counters/ru/ruL70b.gif' },
    ruL61: { src: '/images/counters/ru/ruL61.gif' },
    ruL61b: { src: '/images/counters/ru/ruL61b.gif' },
    ruMMG: { src: '/images/counters/ru/ruMMG.gif' },
    ruMMGb: { src: '/images/counters/ru/ruMMGb.gif' },
    ruLMG: { src: '/images/counters/ru/ruLMG.gif' },
    ruLMGb: { src: '/images/counters/ru/ruLMGb.gif' },

    am747S: { src: '/images/counters/am/am747S.gif' },
    ams8b: { src: '/images/counters/am/ams8b.gif' },

    am337H: { src: '/images/counters/am/am337H.gif' },
    amh7b: { src: '/images/counters/am/amh7b.gif' },

    amL92: { src: '/images/counters/am/amL92.gif' },
    amL92b: { src: '/images/counters/am/amL92b.gif' },
    amL91: { src: '/images/counters/am/amL91.gif' },
    amL91b: { src: '/images/counters/am/amL91b.gif' },
    amL81: { src: '/images/counters/am/amL81.gif' },
    amL81b: { src: '/images/counters/am/amL81b.gif' },
    amL80: { src: '/images/counters/am/amL80.gif' },
    amL80b: { src: '/images/counters/am/amL80b.gif' },
    amL70: { src: '/images/counters/am/amL70.gif' },
    amL70b: { src: '/images/counters/am/amL70b.gif' },
    amL61: { src: '/images/counters/am/amL61.gif' },
    amL61b: { src: '/images/counters/am/amL61b.gif' },

    ge548S: { src: '/images/counters/ge/ge548S.gif' },
    ge467S: { src: '/images/counters/ge/ge467S.gif' },
    ge447S: { src: '/images/counters/ge/ge447S.gif' },
    ge436S: { src: '/images/counters/ge/ge436S.gif' },

    ges8b: { src: '/images/counters/ge/ges8b.gif' },
    ges7b: { src: '/images/counters/ge/ges7b.gif' },
    ges5b: { src: '/images/counters/ge/ges5b.gif' },

    ge238H: { src: '/images/counters/ge/ge238H.gif' },
    ge247H: { src: '/images/counters/ge/ge247H.gif' },
    ge237H: { src: '/images/counters/ge/ge237H.gif' },
    ge236H: { src: '/images/counters/ge/ge236H.gif' },

    geh7b: { src: '/images/counters/ge/geh7b.gif' },
    geh6b: { src: '/images/counters/ge/geh6b.gif' },
    geh4b: { src: '/images/counters/ge/geh4b.gif' },

    geL91: { src: '/images/counters/ge/geL91.gif' },
    geL91b: { src: '/images/counters/ge/geL91b.gif' },
    geL81: { src: '/images/counters/ge/geL81.gif' },
    geL81b: { src: '/images/counters/ge/geL81b.gif' },
    geL80: { src: '/images/counters/ge/geL80.gif' },
    geL80b: { src: '/images/counters/ge/geL80b.gif' },
    geL70: { src: '/images/counters/ge/geL70.gif' },
    geL70b: { src: '/images/counters/ge/geL70b.gif' },
    geL61: { src: '/images/counters/ge/geL61.gif' },
    geL61b: { src: '/images/counters/ge/geL61b.gif' },

    currentHex: { src: '/images/other/CurrentHex.gif' },
    targetHex: { src: '/images/other/TargetHex.gif' },
    defenseFireHex: { src: '/images/other/PerimPN.gif' },
    fireGroupHex: { src: '/images/other/FireGroupHex.gif' },
    prepFire: { src: '/images/counters/ms/FirePrep.gif' },
    finalFire: { src: '/images/counters/ms/Final.gif' },
    advFire: { src: '/images/counters/ms/FireAdv.gif' },
    firstFire: { src: '/images/counters/ms/First.gif' },
    mainMap: { src: '/images/maps/bdy.gif' },
    resid1: { src: '/images/counters/do/Resid01.gif' },
    resid2: { src: '/images/counters/do/Resid02.gif' },
    resid4: { src: '/images/counters/do/Resid04.gif' },
    resid6: { src: '/images/counters/do/Resid06.gif' },
    resid8: { src: '/images/counters/do/Resid08.gif' },
    resid12: { src: '/images/counters/do/Resid12.gif' },
    smoke: { src: '/images/counters/ms/Smk12.gif' },
    melee: { src: '/images/counters/ms/Melee.gif' },
    compass3: { src: '/images/counters/ml/North3.gif' },
    compass1: { src: '/images/counters/ml/North1.gif' },
    blocked: { src: '/images/Blocked.png' },
};